# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

output: prefixed

env:
  POSTGRES_URL: "postgresql://user:password@localhost:5432/eats"

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true
